language: ruby
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx
cache: bundler
sudo: false
matrix:
  allow_failures:
      - rvm: rbx
      - rvm: jruby

