# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically using rdf vocabulary format from http://bibframe.org/vocab/
require 'rdf'
module RDF::Vocab
  # @!parse
  #   # Vocabulary for <http://bibframe.org/vocab/>
  #   class Bibframe < RDF::StrictVocabulary
  #   end
  class Bibframe < RDF::StrictVocabulary("http://bibframe.org/vocab/")

    # Ontology definition
    ontology :"http://bibframe.org/vocab/",
      :"dc:modified" => %(2014-12-10T20:23:05.638677Z).freeze,
      :"owl:versionInfo" => %(Initially automatically generated.).freeze,
      type: "owl:Ontology".freeze

    # Class definitions
    term :Agent,
      comment: %(Entity having a role in a resource \(Person, Organization, etc.\).).freeze,
      label: "Agent".freeze,
      subClassOf: "bibframe:Authority".freeze,
      type: "rdfs:Class".freeze
    term :Annotation,
      comment: %(Resource that asserts additional information about other BIBFRAME resource.).freeze,
      label: "Annotation".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Archival,
      comment: %(Resources organically created, accumulated, and/or used by a person, family, or organization in the course of conduct of affairs and preserved because of their continuing value.).freeze,
      :"dc:modified" => %(2014-10-28 \(Updated\)).freeze,
      label: "Archival controlled".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :Arrangement,
      comment: %(Information about the organization and arrangement of a collection of items. For instance, for computer files, organization and arrangement information may be the file structure and sort sequence of a file; for visual materials, this information may be how a collection is arranged.).freeze,
      label: "Organization of materials information".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Audio,
      comment: %(Resources expressed in an audible form, including music or other sounds.).freeze,
      label: "Audio".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :Authority,
      comment: %(Representation of a key concept or thing. Works and Instances, for example, have defined relationships to these concepts and things.).freeze,
      label: "Authority".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Cartography,
      comment: %(Resource that show spatial information, including maps, atlases, globes,digital maps, and other cartographic items.).freeze,
      label: "Cartography".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :Category,
      comment: %(Generic list of values information.).freeze,
      :"dc:modified" => %(2014-03-21 \(Definition Updated\)).freeze,
      label: "Category".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Classification,
      comment: %(System of coding, assorting and organizing materials according to their subject.).freeze,
      label: "Classification Entity".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Collection,
      comment: %(Aggregation of resources, generally gathered together artificially.).freeze,
      label: "Collection".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :CoverArt,
      comment: %(Link to a cover illustration of an instance.).freeze,
      label: "Cover Art Annotation".freeze,
      subClassOf: "bibframe:Annotation".freeze,
      type: "rdfs:Class".freeze
    term :Dataset,
      comment: %(Data encoded in a defined structure. Includes numeric data, environmental data,etc., used by applications software to calculate averages, correlations, etc., or to produce models, etc., but not normally displayed in its raw form.).freeze,
      label: "Dataset".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :DescriptionAdminInfo,
      comment: %(Administrative metadata associated with the graph.).freeze,
      :"dc:modified" => %(2014-03-21 \(Definition Updated\)).freeze,
      label: "Administrative metadata".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Electronic,
      comment: %(Resource that is intended for manipulation by a computer, residing in a carrier accessed either directly or remotely.).freeze,
      :"dc:modified" => %(2014-10-28 \(Updated\)).freeze,
      label: "Electronic".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :Event,
      comment: %(Time or place of an event.).freeze,
      :"dc:modified" => %(2014-03-21 \(Definition Updated\)).freeze,
      label: "Event Entity".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Family,
      comment: %(Two or more persons related by birth, marriage, adoption, civil union, or similar legal status, or who otherwise present themselves as a family.).freeze,
      label: "Family".freeze,
      subClassOf: "bibframe:Agent".freeze,
      type: "rdfs:Class".freeze
    term :HeldItem,
      comment: %(Item holding information.).freeze,
      :"dc:modified" => %(2014-03-21 \(Label Updated\)).freeze,
      label: "Item held".freeze,
      subClassOf: "bibframe:HeldMaterial".freeze,
      type: "rdfs:Class".freeze
    term :HeldMaterial,
      comment: %(Summary holdings information.).freeze,
      :"dc:modified" => %(2014-03-21 \(Label Updated\)).freeze,
      label: "Material held".freeze,
      subClassOf: "bibframe:Annotation".freeze,
      type: "rdfs:Class".freeze
    term :Identifier,
      comment: %(Token or name that is associated with a resource, such as a URI, or an ISBN, etc..).freeze,
      label: "Identifier".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Instance,
      comment: %(Resource reflecting an individual, material embodiment of the Work.).freeze,
      label: "Instance".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Integrating,
      comment: %(Cataloging resource that is added to or changed by means of updates that do not remain discrete but are integrated into the whole.).freeze,
      label: "Integrating".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :IntendedAudience,
      comment: %(Information that identifies the specific intended or target audience or intellectual level for which the content described item is considered appropriate. Used to record interest and motivation levels and special learner characteristics.).freeze,
      label: "Intended Audience Information".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Jurisdiction,
      comment: %(Legal or political unit administering a geographic area.).freeze,
      label: "Jurisdiction".freeze,
      subClassOf: "bibframe:Agent".freeze,
      type: "rdfs:Class".freeze
    term :Language,
      comment: %(Language entity.).freeze,
      label: "Language Entity".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Manuscript,
      comment: %(Resource that is written in handwriting or typescript. These are generally unique resources.).freeze,
      label: "Manuscript".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :Meeting,
      comment: %(Gathering of individuals or representatives of various bodies for the purpose of discussing and/or acting on topics of common interest.).freeze,
      label: "Meeting".freeze,
      subClassOf: "bibframe:Agent".freeze,
      type: "rdfs:Class".freeze
    term :MixedMaterial,
      comment: %(Resource comprised of multiple types which are not driven by software. This may include materials in two or more forms that are related by virtue of their having been accumulated by or about a person or body, e.g. archival forms.).freeze,
      label: "Mixed Material".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :Monograph,
      comment: %(Single unit cataloging resource.).freeze,
      label: "Single unit".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :MovingImage,
      comment: %(Images intended to be perceived as moving, including motion pictures \(using liveaction and/or animation\), film and video recordings of performances, events,etc.).freeze,
      label: "Moving Image".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :Multimedia,
      comment: %(Electronic resource that is a computer program \(i.e. digitally encoded instructions intended to be processed and performed by a computer\) or which consist of multiple media types that are software driven. Examples include videogames and websites.).freeze,
      label: "Software or Multimedia".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :MultipartMonograph,
      comment: %(Multiple unit cataloging resource that is complete or intended to be completed within a finite number of parts.).freeze,
      label: "Multiple units".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :NotatedMovement,
      comment: %(Graphic, non-realized representations of movement intended to be perceived visually, e.g. dance.).freeze,
      label: "Notated Movement".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :NotatedMusic,
      comment: %(Graphic, non-realized representations of musical works intended to be perceived visually.).freeze,
      label: "Notated Music".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :Organization,
      comment: %(Corporation or group of persons and/or organizations that acts, or may act, as a unit.).freeze,
      label: "Organization".freeze,
      subClassOf: "bibframe:Agent".freeze,
      type: "rdfs:Class".freeze
    term :Person,
      comment: %(Individual or identity established by an individual \(either alone or in collaboration with one or more other individuals\)).freeze,
      label: "Person".freeze,
      subClassOf: "bibframe:Agent".freeze,
      type: "rdfs:Class".freeze
    term :Place,
      comment: %(Geographic location.).freeze,
      label: "Place".freeze,
      subClassOf: "bibframe:Authority".freeze,
      type: "rdfs:Class".freeze
    term :Print,
      comment: %(Resource that is printed.).freeze,
      label: "Printed".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :Provider,
      comment: %(Name of agent relating to the publication, printing, distribution, issue,release, or production of a resource.).freeze,
      label: "Provider Entity".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Relator,
      comment: %(How an agent is related to a resource.).freeze,
      :"dc:modified" => %(2014-04-30 \(New\)).freeze,
      label: "Relationship".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Resource,
      comment: %(Any BIBFRAME object.).freeze,
      label: "Resource".freeze,
      type: "rdfs:Class".freeze
    term :Review,
      comment: %(Critique of a resource, such as a book review, analysis, etc.).freeze,
      label: "Review Annotation".freeze,
      subClassOf: "bibframe:Annotation".freeze,
      type: "rdfs:Class".freeze
    term :Serial,
      comment: %(Multiple unit cataloging resource issued in successive parts that has no predetermined conclusion.).freeze,
      label: "Serial".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :StillImage,
      comment: %(Resource expressed through line, shape, shading, etc., intended to be perceived visually as a still image or images in two dimensions. Includes two-dimensional images and slides and transparencies.).freeze,
      label: "Still Image".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :Summary,
      comment: %(Description of the content of a resource, such as an abstract, summary, etc..).freeze,
      label: "Summary Annotation".freeze,
      subClassOf: "bibframe:Annotation".freeze,
      type: "rdfs:Class".freeze
    term :TableOfContents,
      comment: %(Table of Contents information for a resource.).freeze,
      :"dc:modified" => %(2014-03-21 \(Label Updated\)).freeze,
      label: "Table of Contents Annotation".freeze,
      subClassOf: "bibframe:Annotation".freeze,
      type: "rdfs:Class".freeze
    term :Tactile,
      comment: %(Resource that is intended to be perceived by touch.).freeze,
      label: "Tactile Material".freeze,
      subClassOf: "bibframe:Instance".freeze,
      type: "rdfs:Class".freeze
    term :Temporal,
      comment: %(Chronological period.).freeze,
      label: "Temporal Concept".freeze,
      subClassOf: "bibframe:Authority".freeze,
      type: "rdfs:Class".freeze
    term :Text,
      comment: %(Form of notation for language intended to be perceived visually and understood through the use of language in written or spoken form.).freeze,
      label: "Text".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :ThreeDimensionalObject,
      comment: %(Resource in a form intended to be perceived visually in three-dimensions.Includes man-made objects such as models, sculptures, clothing, and toys, as well as naturally occurring objects such as specimens mounted for viewing.).freeze,
      label: "Three-dimensional Object".freeze,
      subClassOf: "bibframe:Work".freeze,
      type: "rdfs:Class".freeze
    term :Title,
      comment: %(Title information relating to a resource: title proper, translated title, or variant form of title.).freeze,
      label: "Title Entity".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze
    term :Topic,
      comment: %(Concept or area of knowledge.).freeze,
      label: "Topic".freeze,
      subClassOf: "bibframe:Authority".freeze,
      type: "rdfs:Class".freeze
    term :Work,
      comment: %(Resource reflecting a conceptual essence of the cataloging resource.).freeze,
      label: "Work".freeze,
      subClassOf: "bibframe:Resource".freeze,
      type: "rdfs:Class".freeze

    # Property definitions
    property :abbreviatedTitle,
      comment: %(Title as abbreviated for indexing or identification.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Abbreviated title".freeze,
      range: "bibframe:Title".freeze,
      subPropertyOf: "bibframe:instanceTitle".freeze,
      type: "rdf:Property".freeze
    property :absorbed,
      comment: %(Work that has been incorporated into another Work).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Absorbed".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:precededBy".freeze,
      type: "rdf:Property".freeze
    property :absorbedBy,
      comment: %(Work that incorporates another work.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Absorbed by".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:succeededBy".freeze,
      type: "rdf:Property".freeze
    property :absorbedInPart,
      comment: %(Work that has been partially incorporated into another work.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Absorbed in part".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:precededBy".freeze,
      type: "rdf:Property".freeze
    property :absorbedInPartBy,
      comment: %(Work that incorporates part of the content of another work.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Absorbed in part by".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:succeededBy".freeze,
      type: "rdf:Property".freeze
    property :accessCondition,
      comment: %(Allowances and restrictions on access.).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Access condition".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :accompaniedBy,
      comment: %(Resource that has an accompanying resource which adds to it).freeze,
      :"dc:modified" => %(2014-04-10 \(Range updated\)).freeze,
      label: "Accompanied by".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :accompanies,
      comment: %(Resource that adds to or is issued with the described resource).freeze,
      :"dc:modified" => %(2014-04-10 \(Range updated\)).freeze,
      label: "Accompanies".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :agent,
      comment: %(Entity associated with a resource or element of description).freeze,
      label: "Associated agent".freeze,
      range: "bibframe:Authority".freeze,
      type: "rdf:Property".freeze
    property :annotates,
      comment: %(Resource to which the annotation relates.).freeze,
      domain: "bibframe:Annotation".freeze,
      label: "Target of Annotation".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :annotationAssertedBy,
      comment: %(Annotation was asserted by the given entity.).freeze,
      domain: "bibframe:Annotation".freeze,
      label: "Annotation asserted by".freeze,
      range: "bibframe:Agent".freeze,
      type: "rdf:Property".freeze
    property :annotationBody,
      comment: %(Content of the annotation about the resource.).freeze,
      domain: "bibframe:Annotation".freeze,
      label: "Annotation Body".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :annotationSource,
      comment: %(Source of the annotation.).freeze,
      domain: "bibframe:Annotation".freeze,
      label: "Annotation Source".freeze,
      range: "bibframe:Agent".freeze,
      type: "rdf:Property".freeze
    property :ansi,
      comment: %(American National Standards Institute identifier.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "ANSI number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :arrangement,
      comment: %(Information about the organization and arrangement of a collection of resources.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Organization and Arrangement".freeze,
      range: "bibframe:Arrangement".freeze,
      type: "rdf:Property".freeze
    property :aspectRatio,
      comment: %(Proportional relationship between an image's width and its height.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Aspect ratio".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :assertionDate,
      comment: %(Date when annotation was asserted.).freeze,
      domain: "bibframe:Annotation".freeze,
      label: "Annotation Assertion Date".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :audience,
      comment: %(Information that identifies the specific audience or intellectual level for which the content of the resource is considered appropriate.).freeze,
      domain: "bibframe:IntendedAudience".freeze,
      label: "Audience".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :audienceAssigner,
      comment: %(Entity that assigned the intended audience information.).freeze,
      domain: "bibframe:IntendedAudience".freeze,
      label: "Audience assigner".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :authorityAssigner,
      comment: %(Entity that assigned the information.).freeze,
      domain: "bibframe:Authority".freeze,
      label: "Authority assigner".freeze,
      range: "bibframe:Agent".freeze,
      type: "rdf:Property".freeze
    property :authoritySource,
      comment: %(Authority list from which a value is taken.).freeze,
      domain: "bibframe:Authority".freeze,
      label: "Authority source".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :authorizedAccessPoint,
      comment: %(Controlled string form of a resource label intended to help uniquely identify it, such as a unique title or a unique name plus title.).freeze,
      domain: "bibframe:Resource".freeze,
      label: "Authorized access point".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :awardNote,
      comment: %(Information on awards associated with the described resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Award note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :barcode,
      comment: %(Identification number of the physical item.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "Barcode".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :carrierCategory,
      comment: %(Categorization reflecting the format of the storage medium and housing of a carrier.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Carrier type".freeze,
      range: "bibframe:Category".freeze,
      type: "rdf:Property".freeze
    property :cartographicAscensionAndDeclination,
      comment: %(System for identifying the location of a celestial object in the sky covered by the cartographic content of a resource using the angles of right ascension and declination.).freeze,
      domain: "bibframe:Cartography".freeze,
      label: "Cartographic ascension and declination".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :cartographicCoordinates,
      comment: %(Mathematical system for identifying the area covered by the cartographic content of a resource, Expressed either by means of longitude and latitude on the surface of planets or by the angles of right ascension and declination for celestial cartographic content.).freeze,
      domain: "bibframe:Cartography".freeze,
      label: "Cartographic coordinates".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :cartographicEquinox,
      comment: %(One of two points of intersection of the ecliptic and the celestial equator, occupied by the sun when its declination is 0 degrees.).freeze,
      domain: "bibframe:Cartography".freeze,
      label: "Cartographic equinox".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :cartographicExclusionGRing,
      comment: %(Coordinate pairs that identify the closed non-intersecting boundary of the area contained within the G-polygon outer ring that is excluded.).freeze,
      domain: "bibframe:Cartography".freeze,
      label: "Cartographic G ring area excluded".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :cartographicOuterGRing,
      comment: %(Coordinate pairs that identify the closed non-intersecting boundary of the area covered.).freeze,
      domain: "bibframe:Cartography".freeze,
      label: "Cartographic outer G ring area covered".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :cartographicProjection,
      comment: %(Method or system used to represent the surface of the Earth or of a celestial sphere on a plane.).freeze,
      domain: "bibframe:Cartography".freeze,
      label: "Cartographic projection".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :cartographicScale,
      comment: %(Ratio of the dimensions of a form contained or embodied in a resource to the dimensions of the entity it represents.).freeze,
      domain: "bibframe:Cartography".freeze,
      label: "Cartographic scale".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :cartography,
      comment: %(Cartographic data that identifies scale, coordinates, etc.).freeze,
      :"dc:modified" => %(2014-03-27 \(Updated\)).freeze,
      label: "Cartographic data".freeze,
      range: "bibframe:Cartography".freeze,
      type: "rdf:Property".freeze
    property :categorySource,
      comment: %(Category list from which value is taken.).freeze,
      domain: "bibframe:Category".freeze,
      label: "Category source".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :categoryType,
      comment: %(Type of category recorded, e.g., content, genre, media, form, carrier.).freeze,
      domain: "bibframe:Category".freeze,
      label: "Type of category".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :categoryValue,
      comment: %(Category code or text.).freeze,
      domain: "bibframe:Category".freeze,
      label: "Category".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :changeDate,
      comment: %(Date or date and time on which the metadata was modified.).freeze,
      label: "Description change date".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :circulationStatus,
      comment: %(Circulation status of an item.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "Circulation status".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classification,
      comment: %(Classification number in any scheme.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Classification".freeze,
      range: "bibframe:Classification".freeze,
      type: "rdf:Property".freeze
    property :classificationAssigner,
      comment: %(Entity that assigned the classification number.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Institution assigning classification".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationDdc,
      comment: %(Dewey Decimal Classification number used for subject access.).freeze,
      domain: "bibframe:Work".freeze,
      label: "DDC Classification".freeze,
      range: "bibframe:Classification".freeze,
      subPropertyOf: "bibframe:classification".freeze,
      type: "rdf:Property".freeze
    property :classificationDesignation,
      comment: %(Designates whether the classification number contained in the field is from the standard or optional part of the schedules or tables.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification designation".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationEdition,
      comment: %(Edition of the classification scheme, such as full, abridged or a number, when a classification scheme designates editions.).freeze,
      :"dc:modified" => %(2014-10-09 \(Updated\)).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification scheme edition".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationItem,
      comment: %(Number attached to a classification number that indicates a particular item.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification item number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationLcc,
      comment: %(Library of Congress Classification number used for subject access.).freeze,
      domain: "bibframe:Work".freeze,
      label: "LCC Classification".freeze,
      range: "bibframe:Classification".freeze,
      subPropertyOf: "bibframe:classification".freeze,
      type: "rdf:Property".freeze
    property :classificationNlm,
      comment: %(National Library of Medicine Classification number used for subject access).freeze,
      domain: "bibframe:Work".freeze,
      label: "NLM classification".freeze,
      range: "bibframe:Classification".freeze,
      subPropertyOf: "bibframe:classification".freeze,
      type: "rdf:Property".freeze
    property :classificationNumber,
      comment: %(Classification number \(single class number or beginning number of a span\) that indicates the subject by applying a formal system of coding and organizing resources.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationNumberUri,
      comment: %(Classification number represented as a URI.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification number URI".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :classificationScheme,
      comment: %(Formal scheme from which a classification number is taken.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification scheme".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationSpanEnd,
      comment: %(Ending number of classification number span.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification number span end".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationStatus,
      comment: %(Indicator that the classification number is canceled or invalid.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification status".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationTable,
      comment: %(DDC Table identification. Number of the table from which the classification number in a subdivision record is taken.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification table identification".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationTableSeq,
      comment: %(Sequence number or other identifier for an internal classification subarrangement or add in a classification scheme.).freeze,
      domain: "bibframe:Classification".freeze,
      label: "Classification table sequence number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :classificationUdc,
      comment: %(Universal Decimal Classification number used for subject access.).freeze,
      domain: "bibframe:Work".freeze,
      label: "UDC Classification".freeze,
      range: "bibframe:Classification".freeze,
      subPropertyOf: "bibframe:classification".freeze,
      type: "rdf:Property".freeze
    property :coden,
      comment: %(Identifier for scientific and technical periodical titles assigned by the International CODEN Section of Chemical Abstracts Service.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "CODEN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :colorContent,
      comment: %(Color characteristics, e.g. black and white, multicolored, etc.).freeze,
      :"dc:modified" => %(2014-10-14 \(Updated\)).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Color content".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :componentOf,
      comment: %(Link to held material).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "Held item".freeze,
      range: "bibframe:HeldMaterial".freeze,
      type: "rdf:Property".freeze
    property :contentAccessibility,
      comment: %(Content that assists those with a sensory impairment for greater understanding of content, e.g., labels, captions.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Content accessibility note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :contentCategory,
      comment: %(Categorization reflecting the fundamental form of communication in which the content is expressed and the human sense through which it is intended to be perceived.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Content type".freeze,
      range: "bibframe:Category".freeze,
      type: "rdf:Property".freeze
    property :contentsNote,
      comment: %(List of subunits of the resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Contents".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :continuedBy,
      comment: %(Work whose content continues an earlier work under a new title.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Continued by".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:succeededBy".freeze,
      type: "rdf:Property".freeze
    property :continuedInPartBy,
      comment: %(Work part of whose content separated from an earlier work to form a new work.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Continued in part by".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:succeededBy".freeze,
      type: "rdf:Property".freeze
    property :continues,
      comment: %(Work that is continued by the content of a later work under a new title.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Continues".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:precededBy".freeze,
      type: "rdf:Property".freeze
    property :continuesInPart,
      comment: %(Work that split into two or more separate works with new titles.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Continues in part".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:precededBy".freeze,
      type: "rdf:Property".freeze
    property :contributor,
      comment: %(Generalized expressive responsibility role.).freeze,
      label: "Contributor role".freeze,
      range: "bibframe:Authority".freeze,
      type: "rdf:Property".freeze
    property :copyNote,
      comment: %(Information about this copy.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "Copy note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :copyrightDate,
      comment: %(Date associated with a claim of protection under copyright or a similar regime.).freeze,
      domain: "bibframe:Provider".freeze,
      label: "Copyright date".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :coverArt,
      comment: %(Cover art image.).freeze,
      domain: "bibframe:CoverArt".freeze,
      label: "Cover art".freeze,
      range: "rdfs:Resource".freeze,
      subPropertyOf: "bibframe:annotationBody".freeze,
      type: "rdf:Property".freeze
    property :coverArtFor,
      comment: %(Resource to which the cover art pertains.).freeze,
      domain: "bibframe:CoverArt".freeze,
      label: "Cover art of instance".freeze,
      range: "bibframe:Instance".freeze,
      subPropertyOf: "bibframe:annotates".freeze,
      type: "rdf:Property".freeze
    property :coverArtThumb,
      comment: %(Thumbnail version of cover art image.).freeze,
      domain: "bibframe:CoverArt".freeze,
      label: "Thumbnail of cover art".freeze,
      range: "rdfs:Resource".freeze,
      subPropertyOf: "bibframe:annotationBody".freeze,
      type: "rdf:Property".freeze
    property :creationDate,
      comment: %(Date or date and time on which the original metadata first created.).freeze,
      label: "Description creation date".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :creator,
      comment: %(Generalized creative responsibility role.).freeze,
      label: "Creator role".freeze,
      range: "bibframe:Authority".freeze,
      type: "rdf:Property".freeze
    property :creditsNote,
      comment: %(Credits for persons or organizations, other than members of the cast, who have participated in the creation and/or production of the.).freeze,
      label: "Credits note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :custodialHistory,
      comment: %(Information about the provenance, such as origin, ownership and custodial history \(chain of custody\), of a resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Custodial history".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :dataSource,
      comment: %(Work that is a data source to which the described resource is related. It may contain information about other files, printed sources, or collection procedures.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Has data source".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :derivativeOf,
      comment: %(Work is a modification of a source work.).freeze,
      :"dc:modified" => %(2014-04-30 \(New\)).freeze,
      label: "Is derivative of".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :derivedFrom,
      comment: %(Link to the record that was the source of the data, when applicable.).freeze,
      label: "Source record".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :descriptionAuthentication,
      comment: %(Indication of specific types of reviews of description information.).freeze,
      :"dc:modified" => %(2014-10-27 \(Updated\)).freeze,
      label: "Description authentication".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :descriptionConventions,
      comment: %(Rules used for the descriptive content of the description.).freeze,
      :"dc:modified" => %(2014-05-13 \(updated\)).freeze,
      label: "Description conventions".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :descriptionLanguage,
      comment: %(Language used for the metadata.).freeze,
      label: "Description language".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :descriptionModifier,
      comment: %(Agency that modified a description.).freeze,
      :"dc:modified" => %(2014-10-27 \(Updated\)).freeze,
      label: "Description modifier".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :descriptionOf,
      comment: %(Related resource that is analyzed, commented upon, critiqued, evaluated, reviewed, or otherwise described by the resource.).freeze,
      :"dc:modified" => %(2014-04-30 \(New\)).freeze,
      label: "Is description of".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :descriptionSource,
      comment: %(Entity that created or modified the metadata.).freeze,
      label: "Description source".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :descriptionStatus,
      comment: %(Indicaton of whether the description is new or revised or in other states.).freeze,
      :"dc:modified" => %(2014-10-27 \(Updated\)).freeze,
      label: "Description status".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :dimensions,
      comment: %(Measurements of the carrier or carriers and/or the container of a resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Dimensions".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :dissertationDegree,
      comment: %(Degree for which author was a candidate.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Degree".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :dissertationIdentifier,
      comment: %(Identifier assigned to a dissertation for identification purposes .).freeze,
      domain: "bibframe:Work".freeze,
      label: "Dissertation identifier".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :dissertationInstitution,
      comment: %(Name of degree granting institution.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Degree issuing institution".freeze,
      range: "bibframe:Agent".freeze,
      type: "rdf:Property".freeze
    property :dissertationNote,
      comment: %(Textual information about the dissertation.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Dissertation note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :dissertationYear,
      comment: %(Year degree awarded.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Year degree awarded".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :distribution,
      comment: %(Information relating to distribution of an instance.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Distribution event".freeze,
      range: "bibframe:Provider".freeze,
      subPropertyOf: "bibframe:provider".freeze,
      type: "rdf:Property".freeze
    property :doi,
      comment: %(Digital Object Identifier.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "DOI".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :duration,
      comment: %(Information about the playing time or duration in an unstructured form, e.g., "2 hours".).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Duration".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :ean,
      comment: %(International Article Identifier.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "EAN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :edition,
      comment: %(Information identifying the edition or version of the resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Edition statement".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :editionResponsibility,
      comment: %(Statement relating to the identification of any persons, families, or corporate bodies responsible for the edition being described.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Edition responsibility".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :electronicLocator,
      comment: %(Electronic location from which the resource is available.).freeze,
      :"dc:modified" => %(2014-04-28 \(New\)).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Electronic location".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :enumerationAndChronology,
      comment: %(Numbering and dates of holding.).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Enumeration and chronology".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :event,
      comment: %(Information about the geographic area/or time period covered by an event \(e.g., a report\).).freeze,
      :"dc:modified" => %(2014-05-16 \(Updated\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Event associated with content".freeze,
      range: "bibframe:Event".freeze,
      type: "rdf:Property".freeze
    property :eventAgent,
      comment: %(Person or organization associated with event.).freeze,
      :"dc:modified" => %(2014-05-16 \(Updated\)).freeze,
      domain: "bibframe:Event".freeze,
      label: "Agent for event".freeze,
      range: "bibframe:Agent".freeze,
      type: "rdf:Property".freeze
    property :eventDate,
      comment: %(Date, time or period of event.).freeze,
      :"dc:modified" => %(2014-05-16 \(Updated\)).freeze,
      domain: "bibframe:Event".freeze,
      label: "Date(s) of event".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :eventPlace,
      comment: %(Geographic area associated with event.).freeze,
      domain: "bibframe:Event".freeze,
      label: "Place of event".freeze,
      range: "bibframe:Place".freeze,
      type: "rdf:Property".freeze
    property :expressionOf,
      comment: %(Expression has a related work. For use to connect Works under FRBR/RDA rules.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Expression of".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :extent,
      comment: %(Number and type of units and/or subunits making up a resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Extent".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :findingAid,
      comment: %(Relationship is to a finding aid or similar control materials for archival, visual, and manuscript resources.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Has finding aid".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:accompaniedBy".freeze,
      type: "rdf:Property".freeze
    property :findingAidNote,
      comment: %(Note about availability of an index or finding aid.).freeze,
      label: "Index or finding aid note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :fingerprint,
      comment: %(Identifier that is used to assist in the identification of antiquarian books by recording information comprising groups of characters taken from specified positions on specified pages of the book.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Fingerprint identifier".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :formDesignation,
      comment: %(Class or genre to which a Work or Instance belongs.).freeze,
      :"dc:modified" => %(2014-03-21 \(Range updated\)).freeze,
      domain: "bibframe:Title".freeze,
      label: "Form designation".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :format,
      comment: %(File format or physical medium of an instance.).freeze,
      :"dc:modified" => %(2014-10-27 \(Updated\)).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Format".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :formatOfMusic,
      comment: %(Format of a musical composition, e.g. full score, condensed score, vocal score, etc.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Format of music".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :frequency,
      comment: %(Intervals at which the issues or parts of a serial or the updates to an integrating resource are issued.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Frequency".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :frequencyNote,
      comment: %(Current or former publication frequency of a resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Frequency note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :generationDate,
      comment: %(Date of conversion of the data from another format.).freeze,
      :"dc:modified" => %(2014-10-27 \(Updated\)).freeze,
      label: "Date generated".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :generationProcess,
      comment: %(Indication of the program or process used to generate the description by application of a particular transformation.).freeze,
      :"dc:modified" => %(2014-10-27 \(Updated\)).freeze,
      label: "Description generation".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :genre,
      comment: %(Genre and other general characteristics associated with genre and form.).freeze,
      :"dc:modified" => %(2014-03-21 \(New\)).freeze,
      label: "Genre".freeze,
      range: "bibframe:Category".freeze,
      type: "rdf:Property".freeze
    property :geographicCoverageNote,
      comment: %(Geographic entities covered by the resource.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Geographic coverage".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :graphicScaleNote,
      comment: %(Textual information about scale, including the scale of graphic material item such as architectural drawings or three-dimensional artifacts.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Graphic scale".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :hasAccompaniment,
      label: "has accompaniment".freeze,
      type: "rdf:Property".freeze
    property :hasAnnotation,
      comment: %(Resource has an annotation.).freeze,
      label: "Has annotation".freeze,
      range: "bibframe:Annotation".freeze,
      type: "rdf:Property".freeze
    property :hasAuthority,
      comment: %(Link to controlled form of name or subject and other information about.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated range\)).freeze,
      domain: "bibframe:Authority".freeze,
      label: "Authority information".freeze,
      range: "bibframe:Resource".freeze,
      type: "rdf:Property".freeze
    property :hasDerivative,
      comment: %(Work has a modification for which it is the source.).freeze,
      :"dc:modified" => %(2014-04-10 \(Range updated\)).freeze,
      label: "Has derivative".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :hasDescription,
      comment: %(Related resource that analyzes, comments on, critiques, evaluates, reviews, or otherwise describes the resource.).freeze,
      :"dc:modified" => %(2014-04-10 \(Range updated\)).freeze,
      label: "Has description".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :hasEquivalent,
      comment: %(Instance embodies the same expression of a work as the resource being described.).freeze,
      :"dc:modified" => %(2014-04-10 \(Range updated\)).freeze,
      label: "Equivalence".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :hasExpression,
      comment: %(Work has a related expression. For use to connect Works under FRBR/RDA rules.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Expressed as".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :hasInstance,
      comment: %(Work has a related Instance/manifestation. For use to connect Works to Instances in the BIBFRAME structure.).freeze,
      :"dc:modified" => %(2014--03-21 \(Updated definition\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Instance of Work".freeze,
      range: "bibframe:Instance".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :hasPart,
      comment: %(Resource that is included either physically or logically contained in the described resource).freeze,
      :"dc:modified" => %(2014-04-10 \(Range updated\)).freeze,
      label: "Has part".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :hdl,
      comment: %(Unique and persistent identifier for digital objects developed by the Corporation for National Research Initiatives.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Handle".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :heldBy,
      comment: %(Entity holding the item or from which it is available).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Held by".freeze,
      range: "bibframe:Agent".freeze,
      type: "rdf:Property".freeze
    property :holdingFor,
      comment: %(Instance for which holding is reported).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Holding for".freeze,
      range: "bibframe:Instance".freeze,
      subPropertyOf: "bibframe:annotates".freeze,
      type: "rdf:Property".freeze
    property :identifier,
      comment: %(Number or code that uniquely identifies an entity.).freeze,
      domain: "bibframe:Resource".freeze,
      label: "Identifier".freeze,
      range: "bibframe:Identifier".freeze,
      type: "rdf:Property".freeze
    property :identifierAssigner,
      comment: %(Entity that assigned the identifier.).freeze,
      domain: "bibframe:Identifier".freeze,
      label: "Identifier assigner".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :identifierQualifier,
      comment: %(Qualifying information associated with the identifier, e.g. specifying its applicability.).freeze,
      domain: "bibframe:Identifier".freeze,
      label: "Identifier qualifier".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :identifierScheme,
      comment: %(Scheme within which the identifier is unique.).freeze,
      :"dc:modified" => [%('2014-06-04 \(Updated range\)).freeze, %(2014-06-04 \(Updated mapping\)).freeze],
      domain: "bibframe:Identifier".freeze,
      label: "Identifier scheme".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :identifierStatus,
      comment: %(Indication of whether the identifier is canceled or invalid.).freeze,
      domain: "bibframe:Identifier".freeze,
      label: "Identifier status".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :identifierValue,
      comment: %(Value of the identifier.).freeze,
      domain: "bibframe:Identifier".freeze,
      label: "Identifier value".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :illustrationNote,
      comment: %(Information about illustrative material in the resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Illustrative content note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :immediateAcquisition,
      comment: %(Information about the circumstances \(e.g., source, date, method\) under which the resource was directly acquired.).freeze,
      label: "Immediate acquisition".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :index,
      comment: %(Work has an accompanying index).freeze,
      domain: "bibframe:Work".freeze,
      label: "Index".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:accompaniedBy".freeze,
      type: "rdf:Property".freeze
    property :instanceOf,
      comment: %(Work this resource instantiates or manifests. For use to connect Instances to Works in the BIBFRAME structure.).freeze,
      :"dc:modified" => %(2014--03-21 \(Updated definition\)).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Instance of".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :instanceTitle,
      comment: %(Word, character, or group of words and/or characters that is the main name of an instance.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Instance title".freeze,
      range: "bibframe:Title".freeze,
      type: "rdf:Property".freeze
    property :intendedAudience,
      comment: %(Information that identifies the specific audience or intellectual level for which the content of the resource is considered appropriate.).freeze,
      label: "Intended audience".freeze,
      range: "bibframe:IntendedAudience".freeze,
      type: "rdf:Property".freeze
    property :isan,
      comment: %(International Standard Audiovisual Number.).freeze,
      domain: "bibframe:Work".freeze,
      label: "ISAN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :isbn,
      comment: %(International Standard Book Number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "ISBN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :isbn10,
      comment: %(10 digit version of the International Standard Book Number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "ISBN-10".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:isbn".freeze,
      type: "rdf:Property".freeze
    property :isbn13,
      comment: %(13 digit version of the International Standard Book Number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "ISBN-13".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:isbn".freeze,
      type: "rdf:Property".freeze
    property :ismn,
      comment: %(International Standard Music Number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "ISMN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :iso,
      comment: %(International Organization for Standardization standard number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "ISO number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :issn,
      comment: %(International Standard Serial Number identifier.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "ISSN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :issnL,
      comment: %(International Standard Serial Number that links together various media versions of a continuing resource.).freeze,
      domain: "bibframe:Work".freeze,
      label: "ISSN-L".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :issueNumber,
      comment: %(Number used to identify the issue designation, or serial identification, assigned by a publisher to a sound recording.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Audio issue number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :issuedWith,
      comment: %(Instance that is issued on the same carrier as the manifestation being described.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Issued with".freeze,
      range: "bibframe:Instance".freeze,
      subPropertyOf: "bibframe:hasAccompaniment".freeze,
      type: "rdf:Property".freeze
    property :istc,
      comment: %(International Standard Text code, a numbering system developed to enable the unique identification of textual works.).freeze,
      :"dc:modified" => %(a,z).freeze,
      domain: "bibframe:Work".freeze,
      label: "ISTC".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :iswc,
      comment: %(International Standard Musical Work Code, a unique, persistent reference number for the identification of musical works.).freeze,
      domain: "bibframe:Work".freeze,
      label: "ISWC".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :itemId,
      comment: %(Identification number assigned to data about one item held.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "System item identifier".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :keyTitle,
      comment: %(Unique title for a continuing resource that is assigned by the ISSN International Center in conjunction with an ISSN.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Key title".freeze,
      range: "bibframe:Title".freeze,
      subPropertyOf: "bibframe:instanceTitle".freeze,
      type: "rdf:Property".freeze
    property :label,
      comment: %(Text string expressing the property value.).freeze,
      domain: "bibframe:Resource".freeze,
      label: "Label".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :language,
      comment: %(Languages associated with a resource including those for multilingual resources and translated resources.).freeze,
      label: "Language".freeze,
      range: "bibframe:Language".freeze,
      type: "rdf:Property".freeze
    property :languageNote,
      comment: %(Note concerning the language of the material or its parts.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Language note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :languageOfPart,
      comment: %(Language or notation system used to convey the content of the resource \(associated with part or all of a resource\).).freeze,
      domain: "bibframe:Language".freeze,
      label: "Language of part".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :languageOfPartUri,
      comment: %(Language or notation system used to convey the content of the resource \(associated with part or all of a resource\).).freeze,
      domain: "bibframe:Language".freeze,
      label: "Language of part URI".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :languageSource,
      comment: %(Language code or name list from which value is taken.).freeze,
      domain: "bibframe:Language".freeze,
      label: "Language source".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :lcOverseasAcq,
      comment: %(Identification number assigned by the Library of Congress to works acquired through one of its overseas acquisition programs.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "LC acquisition program".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :lccn,
      comment: %(Library of Congress Control Number, which identifies the resource description.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "LCCN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :legalDate,
      comment: %(Date of legal work, or promulgation of a law, or signing of a treaty.).freeze,
      label: "Date of legal work".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :legalDeposit,
      comment: %(Number assigned to a copyright or legal deposit, which Identifies a resource description.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Copyright number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :lendingPolicy,
      comment: %(Policy statement about whether and with what restrictions the holding may be lent).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Lending policy".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :local,
      comment: %(Identifier established locally and not a standard number.).freeze,
      label: "Local identifier".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :manufacture,
      comment: %(Information relating to manufacture of an instance.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Manufacture event".freeze,
      range: "bibframe:Provider".freeze,
      subPropertyOf: "bibframe:provider".freeze,
      type: "rdf:Property".freeze
    property :materialArrangement,
      comment: %(Pattern of arrangement of materials within a unit.).freeze,
      domain: "bibframe:Arrangement".freeze,
      label: "Arrangement of material".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :materialHierarchicalLevel,
      comment: %(Hierarchical position of the described materials relative to other material from the same source.).freeze,
      domain: "bibframe:Arrangement".freeze,
      label: "Hierarchical level of material".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :materialOrganization,
      comment: %(Manner in which resource is divided into smaller units.).freeze,
      domain: "bibframe:Arrangement".freeze,
      label: "Organization of material".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :materialPart,
      comment: %(Part of the resource to which information applies.).freeze,
      domain: "bibframe:Arrangement".freeze,
      label: "Part of material".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :matrixNumber,
      comment: %(Matrix number from the master from which a specific sound recording was pressed.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Audio matrix number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :mediaCategory,
      comment: %(Categorization reflecting the general type of intermediation device required to view, play, run, etc., the content of a resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Media type".freeze,
      range: "bibframe:Category".freeze,
      type: "rdf:Property".freeze
    property :mergedToForm,
      comment: %(One of two or more works that come together to form a new work.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Merged to form".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:succeededBy".freeze,
      type: "rdf:Property".freeze
    property :modeOfIssuance,
      comment: %(Categorization reflecting whether a resource is issued in one or more parts, the way it is updated, and its intended termination.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Mode of issuance".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :musicKey,
      comment: %(Pitch and mode for music.).freeze,
      label: "Music Key".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :musicMedium,
      comment: %(Instrumental, vocal, and/or other medium of performance for which a musical resource was originally conceived, written or performed.).freeze,
      label: "Music medium".freeze,
      range: "rdfs:Resource".freeze,
      type: "rdf:Property".freeze
    property :musicMediumNote,
      comment: %(Instrumental, vocal, and/or other medium of performance for which a musical resource was originally conceived, written or performed.).freeze,
      label: "Music medium note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :musicNumber,
      comment: %(Serial, opus, or thematic number or code for music.).freeze,
      label: "Music number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :musicPlate,
      comment: %(Number assigned by a music publisher to a specific music publication.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Music plate number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :musicPublisherNumber,
      comment: %(Number assigned to a music publication other than an issue, matrix, or plate number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Music publisher number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :musicVersion,
      comment: %(Versions such as arrangements, transcriptions, etc. of music.).freeze,
      :"dc:modified" => %(2014-06-19 \(Example Added\)).freeze,
      label: "Music version".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :nban,
      comment: %(National Bibliography Agency Number, which identifies the resource description.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "NBAN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :nbn,
      comment: %(National Bibliography Number, which identifies the resource description.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "NBN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :notation,
      comment: %(Information on the alphabet, script, or symbol system used to convey the content of the resource, including specialized scripts, typefaces, tactile notation, and musical notation.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Notation system".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :note,
      comment: %(General textual information relating to a resource.).freeze,
      :"dc:modified" => %(2014-10-14 \(Updated\)).freeze,
      label: "Note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :originDate,
      comment: %(Date or date range associated with the creation of the work.).freeze,
      :"dc:modified" => %(2014-07-23 \(Example added\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Associated title date".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :originPlace,
      comment: %(Place from which the creation of the work originated.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Associated title place".freeze,
      range: "bibframe:Place".freeze,
      type: "rdf:Property".freeze
    property :originalVersion,
      comment: %(Instance is the original version of which this resource is a reproduction.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Has original version".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:derivativeOf".freeze,
      type: "rdf:Property".freeze
    property :otherEdition,
      comment: %(Resource has other available editions, for example simultaneously published language editions or reprints.).freeze,
      domain: "bibframe:Work".freeze,
      label: "hasOtherEdition".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:derivativeOf".freeze,
      type: "rdf:Property".freeze
    property :otherPhysicalFormat,
      comment: %(Resource that is manifested in another physical carrier.).freeze,
      :"dc:modified" => %(2014-10-14 \(Updated\)).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Has other physical format".freeze,
      range: "bibframe:Instance".freeze,
      subPropertyOf: "bibframe:hasEquivalent".freeze,
      type: "rdf:Property".freeze
    property :partNumber,
      comment: %(Part or section number of a title.).freeze,
      domain: "bibframe:Title".freeze,
      label: "Part number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :partOf,
      comment: %(Resource in which the described resource is physically or logically contained.).freeze,
      :"dc:modified" => %(2014-04-30 \(New\)).freeze,
      label: "Is part of".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :partTitle,
      comment: %(Part or section name of a title.).freeze,
      domain: "bibframe:Title".freeze,
      label: "Part title".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :performerNote,
      comment: %(Information about the participants, players, narrators, presenters, or performers.).freeze,
      label: "Performer note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :postalRegistration,
      comment: %(Number assigned to a publication for which the specified postal service permits the use of a special mailing class privilege.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Postal registration number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :precededBy,
      comment: %(Resource that precedes the resource being described \(e.g., is earlier in time or before in narrative\).).freeze,
      :"dc:modified" => %(2014-04-10 \(Renamed\)).freeze,
      label: "Preceded By".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :preferredCitation,
      comment: %(Citation to the resource preferred by its custodian.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Preferred citation".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :production,
      comment: %(Information relating to production of an instance.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Production event".freeze,
      range: "bibframe:Provider".freeze,
      subPropertyOf: "bibframe:provider".freeze,
      type: "rdf:Property".freeze
    property :provider,
      comment: %(Place, name, and/or date information relating to the publication, printing, distribution, issue, release, or production instance.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Provider".freeze,
      range: "bibframe:Provider".freeze,
      type: "rdf:Property".freeze
    property :providerDate,
      comment: %(Date associated with the publication, printing, distribution, issue, release or production of the instance.).freeze,
      domain: "bibframe:Provider".freeze,
      label: "Provider date".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :providerName,
      comment: %(Name of the entity responsible for the publication, printing, distribution, issue, release or production of the instance.).freeze,
      domain: "bibframe:Provider".freeze,
      label: "Provider name".freeze,
      range: "bibframe:Agent".freeze,
      type: "rdf:Property".freeze
    property :providerPlace,
      comment: %(Place associated with the publication, printing, distribution, issue, release or production of the instance.).freeze,
      domain: "bibframe:Provider".freeze,
      label: "Provider place".freeze,
      range: "bibframe:Place".freeze,
      type: "rdf:Property".freeze
    property :providerRole,
      comment: %(The type of role played by the provider of an instance, e.g. production, publication, manufacture, distribution.).freeze,
      domain: "bibframe:Provider".freeze,
      label: "Provider role".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :providerStatement,
      comment: %(Transcribed provider statement).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Provider statement".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :publication,
      comment: %(Information relating to publication of an instance.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Publication event".freeze,
      range: "bibframe:Provider".freeze,
      subPropertyOf: "bibframe:provider".freeze,
      type: "rdf:Property".freeze
    property :publisherNumber,
      comment: %(Number assigned by a publisher that is not one of the specific defined types.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Other publisher number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :referenceAuthority,
      comment: %(Link to authority information).freeze,
      :"dc:modified" => %(2014-03-27 \(Updated\)).freeze,
      domain: "bibframe:Authority".freeze,
      label: "Other authority information".freeze,
      range: "bibframe:Resource".freeze,
      type: "rdf:Property".freeze
    property :relatedInstance,
      comment: %(General instance to instance relationship.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Related Instance".freeze,
      range: "bibframe:Instance".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :relatedTo,
      comment: %(Any relationship between work or instance resources.).freeze,
      :"dc:modified" => %(2014-04-10 \(Range updated\)).freeze,
      domain: "bibframe:Resource".freeze,
      label: "Related resource".freeze,
      range: "bibframe:Resource".freeze,
      type: "rdf:Property".freeze
    property :relatedWork,
      comment: %(General work to work relationship.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Related Work".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :relator,
      comment: %(link to role and agent information.).freeze,
      :"dc:modified" => %(2014-04-30 \(New\)).freeze,
      label: "Relationship of agent".freeze,
      range: "bibframe:Relator".freeze,
      type: "rdf:Property".freeze
    property :relatorRole,
      comment: %(Specific role of agent.).freeze,
      :"dc:modified" => %(2014-04-30 \(New\)).freeze,
      domain: "bibframe:Relator".freeze,
      label: "Agent role".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :reportNumber,
      comment: %(Identification number of a report that is not a Standard Technical Report Number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Technical report number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :reproduction,
      comment: %(Instance that reproduces another Instance embodying the same work.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Has reproduction".freeze,
      range: "bibframe:Instance".freeze,
      subPropertyOf: "bibframe:hasEquivalent".freeze,
      type: "rdf:Property".freeze
    property :reproductionPolicy,
      comment: %(Policy statement about whether reproductions of the holding can be made).freeze,
      :"dc:modified" => %(2014-10-21 \(Added\)).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Reproduction policy".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :resourcePart,
      comment: %(Part of a resource for which language is being indicated.).freeze,
      domain: "bibframe:Language".freeze,
      label: "Resource part".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :responsibilityStatement,
      comment: %(Statement relating to the identification and/or function of any persons, families, or corporate bodies responsible for the creation of, or contributing to the content of a resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Edition responsibility".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :retentionPolicy,
      comment: %(Policy statement about how many and/or how long the holdings are retained).freeze,
      :"dc:modified" => %(2014-10-21 \(Added\)).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Retention policy".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :review,
      comment: %(Review content.).freeze,
      domain: "bibframe:Review".freeze,
      label: "Review content".freeze,
      range: "rdfs:Resource".freeze,
      subPropertyOf: "bibframe:annotationBody".freeze,
      type: "rdf:Property".freeze
    property :reviewOf,
      comment: %(Resource to which the review pertains.).freeze,
      domain: "bibframe:Review".freeze,
      label: "Resource reviewed".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:annotates".freeze,
      type: "rdf:Property".freeze
    property :separatedFrom,
      comment: %(Work that spun off a part of its content to form a new work.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Separated from".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:precededBy".freeze,
      type: "rdf:Property".freeze
    property :serialFirstIssue,
      comment: %(Beginning date of an instance and/or the sequential designations.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Serial first issue".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :serialLastIssue,
      comment: %(Ending date of an instance and/or the sequential designations.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Serial last issue".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :series,
      comment: %(Work in which the part has been issued; the title of the larger work appears on the part.).freeze,
      :"dc:modified" => %(2014-10-14 \(Updated\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Has series".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:partOf".freeze,
      type: "rdf:Property".freeze
    property :shelfMark,
      comment: %(Physical location, such as a call number or a special shelf/location indicator.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "Shelf Location".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :shelfMarkDdc,
      comment: %(Shelf mark based on Dewey Decimal Classification.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "DDC call number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :shelfMarkLcc,
      comment: %(Shelf mark based on Library of Congress Classification.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "LCC call number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :shelfMarkNlm,
      comment: %(Shelf mark based on National Library of Medicine Classification.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "NLM call number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :shelfMarkScheme,
      comment: %(Scheme from which a shelf mark is taken.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "Shelf mark scheme".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :shelfMarkUdc,
      comment: %(Shelf mark based on Universal Decimal Classification.).freeze,
      domain: "bibframe:HeldItem".freeze,
      label: "UDC call number".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :sici,
      comment: %(Serial Item and Contribution Identifier.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "SICI".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :soundContent,
      comment: %(Indication of whether the production of sound is an integral part of the resource.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Sound content".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :splitInto,
      comment: %(One of two or more works resulting from the division of an earlier work into separate works.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Split into".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:succeededBy".freeze,
      type: "rdf:Property".freeze
    property :startOfReview,
      comment: %(First part of review.).freeze,
      domain: "bibframe:Review".freeze,
      label: "Review beginning".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :startOfSummary,
      comment: %(First part of description.).freeze,
      domain: "bibframe:Summary".freeze,
      label: "Summary beginning".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :stockNumber,
      comment: %(Identification number such as distributor, publisher, or vendor number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Stock number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :strn,
      comment: %(Standard Technical Report Number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "STRN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :studyNumber,
      comment: %(Identification number for a computer data file.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Study number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :subLocation,
      comment: %(Specific place within the holding entity where the item is located or made available).freeze,
      :"dc:modified" => %(2014-04-28 \(Updated Mapping\)).freeze,
      domain: "bibframe:HeldMaterial".freeze,
      label: "Held in sublocation".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :subject,
      comment: %(Subject term\(s\) describing a resource.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Subject".freeze,
      range: ["bibframe:Authority".freeze, "bibframe:Work".freeze],
      type: "rdf:Property".freeze
    property :subseries,
      comment: %(Work, which is part of another series, in which the part has been issued.).freeze,
      :"dc:modified" => %(2014-10-14 \(Updated\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Has subseries".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:hasPart".freeze,
      type: "rdf:Property".freeze
    property :subseriesOf,
      comment: %(Work in which the part consistently appears; the title of the larger work appears on all issues or parts of the subseries\).).freeze,
      :"dc:modified" => %(2014-10-14 \(Updated\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Subseries of".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:partOf".freeze,
      type: "rdf:Property".freeze
    property :subtitle,
      comment: %(Word, character, or group of words and/or characters that contains the remainder of the title information after the main title.).freeze,
      domain: "bibframe:Title".freeze,
      label: "Subtitle".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :succeededBy,
      comment: %(Resource that succeeds the resource being described \(e.g., later in time or after in a narrative\).).freeze,
      :"dc:modified" => %(2014-04-10 \(Renamed\)).freeze,
      label: "Succeeded By".freeze,
      subPropertyOf: "bibframe:relatedTo".freeze,
      type: "rdf:Property".freeze
    property :summary,
      comment: %(Summary or abstract of the target work or instance.).freeze,
      domain: "bibframe:Summary".freeze,
      label: "Summary content".freeze,
      range: "rdfs:Resource".freeze,
      subPropertyOf: "bibframe:annotationBody".freeze,
      type: "rdf:Property".freeze
    property :summaryOf,
      comment: %(Resource to which the description pertains.).freeze,
      domain: "bibframe:Summary".freeze,
      label: "Resource summarized".freeze,
      subPropertyOf: "bibframe:annotates".freeze,
      type: "rdf:Property".freeze
    property :supersededBy,
      comment: %(Later Work used in place of an earlier work, usually because the later work contains updated or new information.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Superseded by".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:succeededBy".freeze,
      type: "rdf:Property".freeze
    property :supersededInPartBy,
      comment: %(Later Work used in part in place of an earlier work, usually because the later work contains updated or new information.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Superseded in part by".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:succeededBy".freeze,
      type: "rdf:Property".freeze
    property :supersedes,
      comment: %(Earlier work whose content has been replaced by a later work, usually because the later work contains updated or new information.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Supersedes".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:precededBy".freeze,
      type: "rdf:Property".freeze
    property :supersedesInPart,
      comment: %(Earlier work whose content has been partially replaced by a later work, usually because the later work contains updated or new information.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Supersedes in part".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:precededBy".freeze,
      type: "rdf:Property".freeze
    property :supplement,
      comment: %(Work that updates or otherwise complements the predominant work.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Has supplement".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:accompaniedBy".freeze,
      type: "rdf:Property".freeze
    property :supplementTo,
      comment: %(Work that is updated or otherwise complemented by the augmenting work.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Supplement to".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:accompanies".freeze,
      type: "rdf:Property".freeze
    property :supplementaryContentNote,
      comment: %(Information on the presence of one or more bibliographies, discographies, filmographies, and/or other bibliographic references in a described resource or in accompanying material.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Supplementary content note".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :systemNumber,
      comment: %(Control number of a system other than LCCN or NBAN, which Identifies a resource description.).freeze,
      label: "System control number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :tableOfContents,
      comment: %(Table of contents of the target work or instance.).freeze,
      domain: "bibframe:TableOfContents".freeze,
      label: "Table of contents content".freeze,
      range: "rdfs:Resource".freeze,
      subPropertyOf: "bibframe:annotationBody".freeze,
      type: "rdf:Property".freeze
    property :tableOfContentsFor,
      comment: %(Resource to which the table of contents pertains.).freeze,
      domain: "bibframe:TableOfContents".freeze,
      label: "Table of contents of resource".freeze,
      range: "rdfs:Resource".freeze,
      subPropertyOf: "bibframe:annotates".freeze,
      type: "rdf:Property".freeze
    property :temporalCoverageNote,
      comment: %(Time period covered by the resource.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Temporal coverage".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :title,
      comment: %(Word, character, or group of words and/or characters that is a name given to a resource).freeze,
      label: "Title".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :titleAttribute,
      comment: %(Other distinguishing characteristic of a work, such as version, etc..).freeze,
      domain: "bibframe:Title".freeze,
      label: "Other title attribute".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :titleQualifier,
      comment: %(Qualifier of title information to make it unique.).freeze,
      domain: "bibframe:Title".freeze,
      label: "Title qualifier".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :titleSource,
      comment: %(Title list from which title is taken, e.g., list of abbreviated titles.).freeze,
      domain: "bibframe:Title".freeze,
      label: "Title source".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :titleStatement,
      comment: %(Title transcribed from an instance.).freeze,
      :"dc:modified" => %(2014-09-03 \(Updated\)).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Transcribed title".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :titleType,
      comment: %(Type of title variation, e.g., acronym, cover, spine. .).freeze,
      :"dc:modified" => %(2014-08-07 \(Example added\)).freeze,
      domain: "bibframe:Title".freeze,
      label: "Variant title type".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :titleValue,
      comment: %(Title being addressed.).freeze,
      domain: "bibframe:Title".freeze,
      label: "Title".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :titleVariation,
      comment: %(Title associated with the resource that is different from the main title.).freeze,
      label: "Title variation".freeze,
      range: "bibframe:Title".freeze,
      type: "rdf:Property".freeze
    property :titleVariationDate,
      comment: %(Date or sequential designation of title variation.).freeze,
      domain: "bibframe:Title".freeze,
      label: "Variant title date".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :translation,
      comment: %(Work that translates the text of the source entity into a language different from that of the original.).freeze,
      domain: "bibframe:Work".freeze,
      label: "Has translation".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:derivativeOf".freeze,
      type: "rdf:Property".freeze
    property :translationOf,
      comment: %(Work that has been translated, i.e., the text expressed in a language different from that of the original work\).).freeze,
      domain: "bibframe:Work".freeze,
      label: "Translation of".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:hasDerivative".freeze,
      type: "rdf:Property".freeze
    property :treatySignator,
      comment: %(Government of other party that has formally signed a treaty.).freeze,
      :"dc:modified" => %(2014-03-21 \(Range updated\)).freeze,
      label: "Signatory to a treaty".freeze,
      range: "rdfs:Literal".freeze,
      type: "rdf:Property".freeze
    property :unionOf,
      comment: %(One of two or more works which came together to form a new work.).freeze,
      :"dc:modified" => %(2014-04-10 \(Updated subproperty\)).freeze,
      domain: "bibframe:Work".freeze,
      label: "Union of".freeze,
      range: "bibframe:Work".freeze,
      subPropertyOf: "bibframe:precededBy".freeze,
      type: "rdf:Property".freeze
    property :upc,
      comment: %(Universal Product Code.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "UPC".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :uri,
      comment: %(Uniform Resource Identifier.).freeze,
      label: "URI".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :urn,
      comment: %(Uniform Resource Number.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "URN".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :videorecordingNumber,
      comment: %(Number assigned by a publisher to a videorecording.).freeze,
      domain: "bibframe:Instance".freeze,
      label: "Videorecording number".freeze,
      range: "bibframe:Identifier".freeze,
      subPropertyOf: "bibframe:identifier".freeze,
      type: "rdf:Property".freeze
    property :workTitle,
      comment: %(Title or form of title chosen to identify the work, such as a preferred title, preferred title with additions, uniform title, etc..).freeze,
      domain: "bibframe:Work".freeze,
      label: "Work title".freeze,
      range: "bibframe:Title".freeze,
      type: "rdf:Property".freeze
  end
end
