# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically using rdf vocabulary format from http://usefulinc.com/ns/doap#
require 'rdf'
module RDF::Vocab
  # Vocabulary for <http://usefulinc.com/ns/doap#>
  # @!visibility private
  DOAP = Class.new(RDF::StrictVocabulary("http://usefulinc.com/ns/doap#")) do

    # Ontology definition
    ontology :"http://usefulinc.com/ns/doap#",
      "http://purl.org/dc/elements/1.1/creator": "Edd Wilder-James",
      "http://purl.org/dc/elements/1.1/description": "The Description of a Project (DOAP) vocabulary, described using W3C RDF Schema and the Web Ontology Language.",
      "http://purl.org/dc/elements/1.1/format": "application/rdf+xml",
      "http://purl.org/dc/elements/1.1/rights": "Copyright © 2004-2018 Edd Dumbill, Edd Wilder-James",
      "http://purl.org/dc/elements/1.1/title": "Description of a Project (DOAP) vocabulary",
      "http://www.w3.org/2002/07/owl#imports": "http://xmlns.com/foaf/0.1/",
      "http://xmlns.com/foaf/0.1/maker": term(
          "http://xmlns.com/foaf/0.1/mbox": "mailto:edd@usefulinc.com",
          "http://xmlns.com/foaf/0.1/name": "Edd Wilder-James",
          type: "http://xmlns.com/foaf/0.1/Person"
        ),
      type: "http://www.w3.org/2002/07/owl#Ontology"

    # Class definitions
    term :ArchRepository,
      comment: "GNU Arch source code repository.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "GNU Arch repository",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: ["http://www.w3.org/2000/01/rdf-schema#Class", "http://www.w3.org/2002/07/owl#Class"]
    term :BKRepository,
      comment: "BitKeeper source code repository.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "BitKeeper Repository",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: ["http://www.w3.org/2000/01/rdf-schema#Class", "http://www.w3.org/2002/07/owl#Class"]
    term :BazaarBranch,
      comment: "Bazaar source code branch.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Bazaar Branch",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :CVSRepository,
      comment: "CVS source code repository.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "CVS Repository",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: ["http://www.w3.org/2000/01/rdf-schema#Class", "http://www.w3.org/2002/07/owl#Class"]
    term :DarcsRepository,
      comment: "darcs source code repository.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "darcs Repository",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :GitBranch,
      comment: "Git source code branch.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Git Branch",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :GitRepository,
      comment: "Git source code repository.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Git Repository",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :HgRepository,
      comment: "Mercurial source code repository.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Mercurial Repository",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :Project,
      comment: "A project.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Project",
      subClassOf: ["http://xmlns.com/foaf/0.1/Project", "http://xmlns.com/wordnet/1.6/Project"],
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :Repository,
      comment: "Source code repository.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Repository",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :SVNRepository,
      comment: "Subversion source code repository.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Subversion Repository",
      subClassOf: "http://usefulinc.com/ns/doap#Repository",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :Specification,
      comment: "A specification of a system's aspects, technical or otherwise.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Specification",
      subClassOf: "http://www.w3.org/2000/01/rdf-schema#Resource",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"
    term :Version,
      comment: "Version information of a project release.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Version",
      type: "http://www.w3.org/2000/01/rdf-schema#Class"

    # Property definitions
    property :"anon-root",
      comment: "Repository for anonymous access.",
      domain: "http://usefulinc.com/ns/doap#Repository",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "anonymous root",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :audience,
      comment: "Description of target user base",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "audience",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :blog,
      comment: "URI of a blog related to a project",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "blog",
      range: ["http://rdfs.org/sioc/types#Weblog", "http://www.w3.org/2000/01/rdf-schema#Resource"],
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :browse,
      comment: "Web browser interface to repository.",
      domain: "http://usefulinc.com/ns/doap#Repository",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "browse",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"bug-database",
      comment: "Bug tracker for a project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "bug database",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :category,
      comment: "A category of project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "category",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :created,
      comment: "Date when something was created, in YYYY-MM-DD form. e.g. 2004-04-05",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "created",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :description,
      comment: "Plain text description of a project, of 2-4 sentences in length.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "description",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :developer,
      comment: "Developer of software for the project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "developer",
      range: "http://xmlns.com/foaf/0.1/Person",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"developer-forum",
      comment: "A forum or community for developers of this project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "developer forum",
      range: "http://rdfs.org/sioc/ns#Container",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :documenter,
      comment: "Contributor of documentation to the project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "documenter",
      range: "http://xmlns.com/foaf/0.1/Person",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"download-mirror",
      comment: "Mirror of software download web page.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "download mirror",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"download-page",
      comment: "Web page from which the project software can be downloaded.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "download page",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"file-release",
      comment: "URI of download associated with this release.",
      domain: "http://usefulinc.com/ns/doap#Version",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "file-release",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :helper,
      comment: "Project contributor.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "helper",
      range: "http://xmlns.com/foaf/0.1/Person",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :homepage,
      comment: "URL of a project's homepage,\n\t\tassociated with exactly one project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "homepage",
      subPropertyOf: "http://xmlns.com/foaf/0.1/homepage",
      type: ["http://www.w3.org/1999/02/22-rdf-syntax-ns#Property", "http://www.w3.org/2002/07/owl#InverseFunctionalProperty"]
    property :implements,
      comment: "A specification that a project implements. Could be a standard, API or legally defined level of conformance.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "Implements specification",
      range: "http://usefulinc.com/ns/doap#Specification",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :language,
      comment: "ISO language code a project has been translated into",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "language",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :license,
      comment: "The URI of an RDF description of the license the software is distributed under. E.g. a SPDX reference",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "license",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :location,
      comment: "Location of a repository.",
      domain: "http://usefulinc.com/ns/doap#Repository",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "repository location",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"mailing-list",
      comment: "Mailing list home page or email address.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "mailing list",
      range: "http://rdfs.org/sioc/types#MailingList",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :maintainer,
      comment: "Maintainer of a project, a project leader.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "maintainer",
      range: "http://xmlns.com/foaf/0.1/Person",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :module,
      comment: "Module name of a Subversion, CVS, BitKeeper or Arch repository.",
      domain: term(
          type: "http://www.w3.org/2002/07/owl#Class",
          unionOf: list("http://usefulinc.com/ns/doap#CVSRepository", "http://usefulinc.com/ns/doap#ArchRepository", "http://usefulinc.com/ns/doap#BKRepository")
        ),
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "module",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :name,
      comment: "A name of something.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "name",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      subPropertyOf: "http://www.w3.org/2000/01/rdf-schema#label",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"old-homepage",
      comment: "URL of a project's past homepage,\n\t\tassociated with exactly one project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "old homepage",
      subPropertyOf: "http://xmlns.com/foaf/0.1/homepage",
      type: ["http://www.w3.org/1999/02/22-rdf-syntax-ns#Property", "http://www.w3.org/2002/07/owl#InverseFunctionalProperty"]
    property :os,
      comment: ["Operating system that a project is limited to.  Omit this property if the project is not OS-specific.", "Sistema operativo a que o projeto está limitado. Omita esta propriedade se o projeto não é condicionado pelo SO usado."],
      domain: ["http://usefulinc.com/ns/doap#Project", "http://usefulinc.com/ns/doap#Version"],
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "operating system",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :platform,
      comment: "Indicator of software platform (non-OS specific), e.g. Java, Firefox, ECMA CLR",
      domain: ["http://usefulinc.com/ns/doap#Project", "http://usefulinc.com/ns/doap#Version"],
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "platform",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"programming-language",
      comment: "Programming language a project is implemented in or intended for use with.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "programming language",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :release,
      comment: "A project release.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "release",
      range: "http://usefulinc.com/ns/doap#Version",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :repository,
      comment: "Source code repository.",
      domain: "http://usefulinc.com/ns/doap#Project",
      inverseOf: "http://usefulinc.com/ns/doap#repositoryOf",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "repository",
      range: "http://usefulinc.com/ns/doap#Repository",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :repositoryOf,
      comment: "The project that uses a repository.",
      domain: "http://usefulinc.com/ns/doap#Repository",
      inverseOf: "http://usefulinc.com/ns/doap#repository",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "repository of",
      range: "http://usefulinc.com/ns/doap#Project",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :revision,
      comment: "Revision identifier of a software release.",
      domain: "http://usefulinc.com/ns/doap#Version",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "revision",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :screenshots,
      comment: "Web page with screenshots of project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "screenshots",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"service-endpoint",
      comment: "The URI of a web service endpoint where software as a service may be accessed",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "service endpoint",
      range: "http://www.w3.org/2000/01/rdf-schema#Resource",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :shortdesc,
      comment: "Short (8 or 9 words) plain text description of a project.",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "short description",
      range: "http://www.w3.org/2000/01/rdf-schema#Literal",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :"support-forum",
      comment: "A forum or community that supports this project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "supporting forum",
      range: "http://rdfs.org/sioc/ns#Container",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :tester,
      comment: "A tester or other quality control contributor.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "tester",
      range: "http://xmlns.com/foaf/0.1/Person",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :translator,
      comment: "Contributor of translations to the project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "translator",
      range: "http://xmlns.com/foaf/0.1/Person",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :vendor,
      comment: "Vendor organization: commercial, free or otherwise",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "vendor",
      range: "http://xmlns.com/foaf/0.1/Organization",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    property :wiki,
      comment: "URL of Wiki for collaborative discussion of project.",
      domain: "http://usefulinc.com/ns/doap#Project",
      isDefinedBy: "http://usefulinc.com/ns/doap#",
      label: "wiki",
      range: "http://rdfs.org/sioc/types#Wiki",
      type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
  end
end
