# -*- encoding: utf-8 -*-
# frozen_string_literal: true
# This file generated automatically using rdf vocabulary format from http://id.loc.gov/vocabulary/identifiers/
require 'rdf'
module RDF::Vocab
  # @!parse
  #   # Vocabulary for <http://id.loc.gov/vocabulary/identifiers/>
  #   class Identifiers < RDF::StrictVocabulary
  #   end
  class Identifiers < RDF::StrictVocabulary("http://id.loc.gov/vocabulary/identifiers/")

    # Ontology definition
    ontology :"http://id.loc.gov/vocabulary/identifiers",
      comment: %(                              Standard Identifiers Scheme  lists standard number or code systems and assigns a URI to each database or publication that defines or contains the identifiers. The purpose of these source codes is to enable the type of standard numbers or codes in resource descriptions to be indicated by URI.               ).freeze,
      label: "Standard Identifiers Scheme".freeze,
      :"mads:hasTopMemberOfMADSScheme" => [%(identifiers:ansi).freeze, %(identifiers:danacode).freeze, %(identifiers:doi).freeze, %(identifiers:ean).freeze, %(identifiers:eidr).freeze, %(identifiers:gtin-14).freeze, %(identifiers:hdl).freeze, %(identifiers:isan).freeze, %(identifiers:isbn).freeze, %(identifiers:isbn-a).freeze, %(identifiers:ismn).freeze, %(identifiers:isni).freeze, %(identifiers:iso).freeze, %(identifiers:isrc).freeze, %(identifiers:issn).freeze, %(identifiers:issn-l).freeze, %(identifiers:issue-number).freeze, %(identifiers:istc).freeze, %(identifiers:iswc).freeze, %(identifiers:itar).freeze, %(identifiers:lccn).freeze, %(identifiers:local).freeze, %(identifiers:matrix-number).freeze, %(identifiers:music-plate).freeze, %(identifiers:music-publisher).freeze, %(identifiers:natgazfid).freeze, %(identifiers:nipo).freeze, %(identifiers:orcid).freeze, %(identifiers:rid).freeze, %(identifiers:scopus).freeze, %(identifiers:sici).freeze, %(identifiers:stock-number).freeze, %(identifiers:strn).freeze, %(identifiers:upc).freeze, %(identifiers:uri).freeze, %(identifiers:urn).freeze, %(identifiers:viaf).freeze, %(identifiers:videorecording-identifier).freeze],
      :"skos:hasTopConcept" => [%(identifiers:ansi).freeze, %(identifiers:danacode).freeze, %(identifiers:doi).freeze, %(identifiers:ean).freeze, %(identifiers:eidr).freeze, %(identifiers:gtin-14).freeze, %(identifiers:hdl).freeze, %(identifiers:isan).freeze, %(identifiers:isbn).freeze, %(identifiers:isbn-a).freeze, %(identifiers:ismn).freeze, %(identifiers:isni).freeze, %(identifiers:iso).freeze, %(identifiers:isrc).freeze, %(identifiers:issn).freeze, %(identifiers:issn-l).freeze, %(identifiers:issue-number).freeze, %(identifiers:istc).freeze, %(identifiers:iswc).freeze, %(identifiers:itar).freeze, %(identifiers:lccn).freeze, %(identifiers:local).freeze, %(identifiers:matrix-number).freeze, %(identifiers:music-plate).freeze, %(identifiers:music-publisher).freeze, %(identifiers:natgazfid).freeze, %(identifiers:nipo).freeze, %(identifiers:orcid).freeze, %(identifiers:rid).freeze, %(identifiers:scopus).freeze, %(identifiers:sici).freeze, %(identifiers:stock-number).freeze, %(identifiers:strn).freeze, %(identifiers:upc).freeze, %(identifiers:uri).freeze, %(identifiers:urn).freeze, %(identifiers:viaf).freeze, %(identifiers:videorecording-identifier).freeze],
      type: ["mads:MADSScheme".freeze, "skos:ConceptScheme".freeze]

    # Property definitions
    property :ansi,
      label: "American National Standards Institute and National Information Standards Organisation number for an ANSI or ANSI/NISO standard".freeze,
      :"mads:authoritativeLabel" => %(American National Standards Institute and National Information Standards Organisation number for an ANSI or ANSI/NISO standard).freeze,
      :"mads:code" => %(ansi).freeze,
      :"skos:notation" => %(ansi).freeze,
      :"skos:prefLabel" => %(American National Standards Institute and National Information Standards Organisation number for an ANSI or ANSI/NISO standard).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :danacode,
      label: "Danacode (Bnei Brak, Israel: D.A.N.A. Systems)".freeze,
      :"mads:authoritativeLabel" => %(Danacode \(Bnei Brak, Israel: D.A.N.A. Systems\)).freeze,
      :"mads:code" => %(danacode).freeze,
      :"skos:notation" => %(danacode).freeze,
      :"skos:prefLabel" => %(Danacode \(Bnei Brak, Israel: D.A.N.A. Systems\)).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :doi,
      label: "Digital Object Identifier".freeze,
      :"mads:authoritativeLabel" => %(Digital Object Identifier).freeze,
      :"mads:code" => %(doi).freeze,
      :"skos:notation" => %(doi).freeze,
      :"skos:prefLabel" => %(Digital Object Identifier).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :ean,
      label: "International Article Number".freeze,
      :"mads:authoritativeLabel" => %(International Article Number).freeze,
      :"mads:code" => %(ean).freeze,
      :"skos:notation" => %(ean).freeze,
      :"skos:prefLabel" => %(International Article Number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :eidr,
      label: "EIDR: Entertainment Identifier Registry".freeze,
      :"mads:authoritativeLabel" => %(EIDR: Entertainment Identifier Registry).freeze,
      :"mads:code" => %(eidr).freeze,
      :"skos:notation" => %(eidr).freeze,
      :"skos:prefLabel" => %(EIDR: Entertainment Identifier Registry).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"gtin-14",
      label: "Global Trade Identification Number 14 (EAN/UCC-128 or ITF-14)".freeze,
      :"mads:authoritativeLabel" => %(Global Trade Identification Number 14 \(EAN/UCC-128 or ITF-14\)).freeze,
      :"mads:code" => %(gtin-14).freeze,
      :"skos:notation" => %(gtin-14).freeze,
      :"skos:prefLabel" => %(Global Trade Identification Number 14 \(EAN/UCC-128 or ITF-14\)).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :hdl,
      label: "Handle".freeze,
      :"mads:authoritativeLabel" => %(Handle).freeze,
      :"mads:code" => %(hdl).freeze,
      :"skos:notation" => %(hdl).freeze,
      :"skos:prefLabel" => %(Handle).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :id,
      comment: %(Generic Identifier property.  It is expected that one will use one of its many subproperties.).freeze,
      label: "Identifier".freeze,
      type: "rdf:Property".freeze
    property :isan,
      label: "International Standard Audiovisual Number".freeze,
      :"mads:authoritativeLabel" => %(International Standard Audiovisual Number).freeze,
      :"mads:code" => %(isan).freeze,
      :"skos:notation" => %(isan).freeze,
      :"skos:prefLabel" => %(International Standard Audiovisual Number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :isbn,
      label: "International Standard Book Number".freeze,
      :"mads:authoritativeLabel" => %(International Standard Book Number).freeze,
      :"mads:code" => %(isbn).freeze,
      :"skos:notation" => %(isbn).freeze,
      :"skos:prefLabel" => %(International Standard Book Number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"isbn-a",
      label: "International Standard Book Number (the actionable ISBN)".freeze,
      :"mads:authoritativeLabel" => %(International Standard Book Number \(the actionable ISBN\)).freeze,
      :"mads:code" => %(isbn-a).freeze,
      :"skos:notation" => %(isbn-a).freeze,
      :"skos:prefLabel" => %(International Standard Book Number \(the actionable ISBN\)).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :ismn,
      label: "International Standard Music Number".freeze,
      :"mads:authoritativeLabel" => %(International Standard Music Number).freeze,
      :"mads:code" => %(ismn).freeze,
      :"skos:notation" => %(ismn).freeze,
      :"skos:prefLabel" => %(International Standard Music Number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :isni,
      label: "International Standard Name Identifier".freeze,
      :"mads:authoritativeLabel" => %(International Standard Name Identifier).freeze,
      :"mads:code" => %(isni).freeze,
      :"skos:notation" => %(isni).freeze,
      :"skos:prefLabel" => %(International Standard Name Identifier).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :iso,
      label: "International Organization for Standardization number for an ISO standard".freeze,
      :"mads:authoritativeLabel" => %(International Organization for Standardization number for an ISO standard).freeze,
      :"mads:code" => %(iso).freeze,
      :"skos:notation" => %(iso).freeze,
      :"skos:prefLabel" => %(International Organization for Standardization number for an ISO standard).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :isrc,
      label: "International Standard Recording Code".freeze,
      :"mads:authoritativeLabel" => %(International Standard Recording Code).freeze,
      :"mads:code" => %(isrc).freeze,
      :"skos:notation" => %(isrc).freeze,
      :"skos:prefLabel" => %(International Standard Recording Code).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :issn,
      label: "International Standard Serial Number".freeze,
      :"mads:authoritativeLabel" => %(International Standard Serial Number).freeze,
      :"mads:code" => %(issn).freeze,
      :"skos:notation" => %(issn).freeze,
      :"skos:prefLabel" => %(International Standard Serial Number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"issn-l",
      label: "Linking International Standard Serial Number".freeze,
      :"mads:authoritativeLabel" => %(Linking International Standard Serial Number).freeze,
      :"mads:code" => %(issn-l).freeze,
      :"skos:notation" => %(issn-l).freeze,
      :"skos:prefLabel" => %(Linking International Standard Serial Number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"issue-number",
      label: "Sound recording issue number".freeze,
      :"mads:authoritativeLabel" => %(Sound recording issue number).freeze,
      :"mads:code" => %(issue-number).freeze,
      :"skos:notation" => %(issue-number).freeze,
      :"skos:prefLabel" => %(Sound recording issue number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :istc,
      label: "International Standard Text Code".freeze,
      :"mads:authoritativeLabel" => %(International Standard Text Code).freeze,
      :"mads:code" => %(istc).freeze,
      :"skos:notation" => %(istc).freeze,
      :"skos:prefLabel" => %(International Standard Text Code).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :iswc,
      label: "International Standard Musical Work Code".freeze,
      :"mads:authoritativeLabel" => %(International Standard Musical Work Code).freeze,
      :"mads:code" => %(iswc).freeze,
      :"skos:notation" => %(iswc).freeze,
      :"skos:prefLabel" => %(International Standard Musical Work Code).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :itar,
      label: "ITAR (Importtjeneste og autoritetsregistre)".freeze,
      :"mads:authoritativeLabel" => %(ITAR \(Importtjeneste og autoritetsregistre\)).freeze,
      :"mads:code" => %(itar).freeze,
      :"skos:notation" => %(itar).freeze,
      :"skos:prefLabel" => %(ITAR \(Importtjeneste og autoritetsregistre\)).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :lccn,
      label: "Library of Congress Control Number".freeze,
      :"mads:authoritativeLabel" => %(Library of Congress Control Number).freeze,
      :"mads:code" => %(lccn).freeze,
      :"skos:notation" => %(lccn).freeze,
      :"skos:prefLabel" => %(Library of Congress Control Number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :local,
      label: "Locally defined identifier".freeze,
      :"mads:authoritativeLabel" => %(Locally defined identifier).freeze,
      :"mads:code" => %(local).freeze,
      :"skos:notation" => %(local).freeze,
      :"skos:prefLabel" => %(Locally defined identifier).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"matrix-number",
      label: "Sound recording matrix number".freeze,
      :"mads:authoritativeLabel" => %(Sound recording matrix number).freeze,
      :"mads:code" => %(matrix-number).freeze,
      :"skos:notation" => %(matrix-number).freeze,
      :"skos:prefLabel" => %(Sound recording matrix number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"music-plate",
      label: "Publisher's music plate number".freeze,
      :"mads:authoritativeLabel" => %(Publisher's music plate number).freeze,
      :"mads:code" => %(music-plate).freeze,
      :"skos:notation" => %(music-plate).freeze,
      :"skos:prefLabel" => %(Publisher's music plate number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"music-publisher",
      label: "Publisher-assigned music number".freeze,
      :"mads:authoritativeLabel" => %(Publisher-assigned music number).freeze,
      :"mads:code" => %(music-publisher).freeze,
      :"skos:notation" => %(music-publisher).freeze,
      :"skos:prefLabel" => %(Publisher-assigned music number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :natgazfid,
      label: "U.S. National Gazetteer Feature Name Identifier".freeze,
      :"mads:authoritativeLabel" => %(U.S. National Gazetteer Feature Name Identifier).freeze,
      :"mads:code" => %(natgazfid).freeze,
      :"skos:notation" => %(natgazfid).freeze,
      :"skos:prefLabel" => %(U.S. National Gazetteer Feature Name Identifier).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :nipo,
      label: "Número de Identificación de las Publicaciones Oficiales".freeze,
      :"mads:authoritativeLabel" => %(Número de Identificación de las Publicaciones Oficiales).freeze,
      :"mads:code" => %(nipo).freeze,
      :"skos:notation" => %(nipo).freeze,
      :"skos:prefLabel" => %(Número de Identificación de las Publicaciones Oficiales).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :orcid,
      label: "Open Researcher and Contributor Identifier".freeze,
      :"mads:authoritativeLabel" => %(Open Researcher and Contributor Identifier).freeze,
      :"mads:code" => %(orcid).freeze,
      :"skos:notation" => %(orcid).freeze,
      :"skos:prefLabel" => %(Open Researcher and Contributor Identifier).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :rid,
      label: "ResearcherID (Thomson Reuters)".freeze,
      :"mads:authoritativeLabel" => %(ResearcherID \(Thomson Reuters\)).freeze,
      :"mads:code" => %(rid).freeze,
      :"skos:notation" => %(rid).freeze,
      :"skos:prefLabel" => %(ResearcherID \(Thomson Reuters\)).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :scopus,
      label: "Scopus Author Identifier".freeze,
      :"mads:authoritativeLabel" => %(Scopus Author Identifier).freeze,
      :"mads:code" => %(scopus).freeze,
      :"skos:notation" => %(scopus).freeze,
      :"skos:prefLabel" => %(Scopus Author Identifier).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :sici,
      label: "Serial Item and Contribution Identifier".freeze,
      :"mads:authoritativeLabel" => %(Serial Item and Contribution Identifier).freeze,
      :"mads:code" => %(sici).freeze,
      :"skos:notation" => %(sici).freeze,
      :"skos:prefLabel" => %(Serial Item and Contribution Identifier).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"stock-number",
      label: "Publisher, distributor, or vendor stock number".freeze,
      :"mads:authoritativeLabel" => %(Publisher, distributor, or vendor stock number).freeze,
      :"mads:code" => %(stock-number).freeze,
      :"skos:notation" => %(stock-number).freeze,
      :"skos:prefLabel" => %(Publisher, distributor, or vendor stock number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :strn,
      label: "Standard Technical Report Number".freeze,
      :"mads:authoritativeLabel" => %(Standard Technical Report Number).freeze,
      :"mads:code" => %(strn).freeze,
      :"skos:notation" => %(strn).freeze,
      :"skos:prefLabel" => %(Standard Technical Report Number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :upc,
      label: "Universal Product Code".freeze,
      :"mads:authoritativeLabel" => %(Universal Product Code).freeze,
      :"mads:code" => %(upc).freeze,
      :"skos:notation" => %(upc).freeze,
      :"skos:prefLabel" => %(Universal Product Code).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :uri,
      label: "Uniform Resource Identifier".freeze,
      :"mads:authoritativeLabel" => %(Uniform Resource Identifier).freeze,
      :"mads:code" => %(uri).freeze,
      :"skos:notation" => %(uri).freeze,
      :"skos:prefLabel" => %(Uniform Resource Identifier).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :urn,
      label: "Uniform Resource Name".freeze,
      :"mads:authoritativeLabel" => %(Uniform Resource Name).freeze,
      :"mads:code" => %(urn).freeze,
      :"skos:notation" => %(urn).freeze,
      :"skos:prefLabel" => %(Uniform Resource Name).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :viaf,
      label: "Virtual International Authority File number".freeze,
      :"mads:authoritativeLabel" => %(Virtual International Authority File number).freeze,
      :"mads:code" => %(viaf).freeze,
      :"skos:notation" => %(viaf).freeze,
      :"skos:prefLabel" => %(Virtual International Authority File number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
    property :"videorecording-identifier",
      label: "Publisher-assigned videorecording number".freeze,
      :"mads:authoritativeLabel" => %(Publisher-assigned videorecording number).freeze,
      :"mads:code" => %(videorecording-identifier).freeze,
      :"skos:notation" => %(videorecording-identifier).freeze,
      :"skos:prefLabel" => %(Publisher-assigned videorecording number).freeze,
      subPropertyOf: "identifiers:id".freeze,
      type: ["mads:Authority".freeze, "rdf:Property".freeze, "skos:Concept".freeze]
  end
end
